from django.db import models

class fooddata(models.Model):
    area_abbreviation_1 = models.CharField(max_length=255)
    area_abbreviation_2 = models.CharField(max_length=255)
    area_abbreviation_3 = models.CharField(max_length=255)
    item_code = models.IntegerField()
    element_code = models.IntegerField()
    element = models.CharField(max_length=255)
    unit = models.CharField(max_length=255)
    latitude = models.FloatField()
    longitude = models.FloatField()
    Y1961 = models.FloatField(null=True, blank=True)
    Y1962 = models.FloatField(null=True, blank=True)
    Y1963 = models.FloatField(null=True, blank=True)
    Y1964 = models.FloatField(null=True, blank=True)
    Y1965 = models.FloatField(null=True, blank=True)
    Y1966 = models.FloatField(null=True, blank=True)
    Y1967 = models.FloatField(null=True, blank=True)
    Y1968 = models.FloatField(null=True, blank=True)
    Y1969 = models.FloatField(null=True, blank=True)
    Y1970 = models.FloatField(null=True, blank=True)
    Y1971 = models.FloatField(null=True, blank=True)
    Y1972 = models.FloatField(null=True, blank=True)
    Y1973 = models.FloatField(null=True, blank=True)
    Y1974 = models.FloatField(null=True, blank=True)
    Y1975 = models.FloatField(null=True, blank=True)
    Y1976 = models.FloatField(null=True, blank=True)
    Y1977 = models.FloatField(null=True, blank=True)
    Y1978 = models.FloatField(null=True, blank=True)
    Y1979 = models.FloatField(null=True, blank=True)
    Y1980 = models.FloatField(null=True, blank=True)
    Y1981 = models.FloatField(null=True, blank=True)
    Y1982 = models.FloatField(null=True, blank=True)
    Y1983 = models.FloatField(null=True, blank=True)
    Y1984 = models.FloatField(null=True, blank=True)
    Y1985 = models.FloatField(null=True, blank=True)
    Y1986 = models.FloatField(null=True, blank=True)
    Y1987 = models.FloatField(null=True, blank=True)
    Y1988 = models.FloatField(null=True, blank=True)
    Y1989 = models.FloatField(null=True, blank=True)
    Y1990 = models.FloatField(null=True, blank=True)
    Y1991 = models.FloatField(null=True, blank=True)
    Y1992 = models.FloatField(null=True, blank=True)
    Y1993 = models.FloatField(null=True, blank=True)
    Y1994 = models.FloatField(null=True, blank=True)
    Y1995 = models.FloatField(null=True, blank=True)
    Y1996 = models.FloatField(null=True, blank=True)
    Y1997 = models.FloatField(null=True, blank=True)
    Y1998 = models.FloatField(null=True, blank=True)
    Y1999 = models.FloatField(null=True, blank=True)
    Y2000 = models.FloatField(null=True, blank=True)
    Y2001 = models.FloatField(null=True, blank=True)
    Y2002 = models.FloatField(null=True, blank=True)
    Y2003 = models.FloatField(null=True, blank=True)
    Y2004 = models.FloatField(null=True, blank=True)
    Y2005 = models.FloatField(null=True, blank=True)
    Y2006 = models.FloatField(null=True, blank=True)
    Y2007 = models.FloatField(null=True, blank=True)
    Y2008 = models.FloatField(null=True, blank=True)
    Y2009 = models.FloatField(null=True, blank=True)
    Y2010 = models.FloatField(null=True, blank=True)
    Y2011 = models.FloatField(null=True, blank=True)
    Y2012 = models.FloatField(null=True, blank=True)
    Y2013 = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.area_abbreviation_1


