# Generated by Django 4.2.7 on 2023-12-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fooddata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_abbreviation_1', models.CharField(max_length=255)),
                ('area_abbreviation_2', models.CharField(max_length=255)),
                ('area_abbreviation_3', models.CharField(max_length=255)),
                ('item_code', models.IntegerField()),
                ('element_code', models.IntegerField()),
                ('element', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('Y1961', models.FloatField(blank=True, null=True)),
                ('Y1962', models.FloatField(blank=True, null=True)),
                ('Y1963', models.FloatField(blank=True, null=True)),
                ('Y1964', models.FloatField(blank=True, null=True)),
                ('Y1965', models.FloatField(blank=True, null=True)),
                ('Y1966', models.FloatField(blank=True, null=True)),
                ('Y1967', models.FloatField(blank=True, null=True)),
                ('Y1968', models.FloatField(blank=True, null=True)),
                ('Y1969', models.FloatField(blank=True, null=True)),
                ('Y1970', models.FloatField(blank=True, null=True)),
                ('Y1971', models.FloatField(blank=True, null=True)),
                ('Y1972', models.FloatField(blank=True, null=True)),
                ('Y1973', models.FloatField(blank=True, null=True)),
                ('Y1974', models.FloatField(blank=True, null=True)),
                ('Y1975', models.FloatField(blank=True, null=True)),
                ('Y1976', models.FloatField(blank=True, null=True)),
                ('Y1977', models.FloatField(blank=True, null=True)),
                ('Y1978', models.FloatField(blank=True, null=True)),
                ('Y1979', models.FloatField(blank=True, null=True)),
                ('Y1980', models.FloatField(blank=True, null=True)),
                ('Y1981', models.FloatField(blank=True, null=True)),
                ('Y1982', models.FloatField(blank=True, null=True)),
                ('Y1983', models.FloatField(blank=True, null=True)),
                ('Y1984', models.FloatField(blank=True, null=True)),
                ('Y1985', models.FloatField(blank=True, null=True)),
                ('Y1986', models.FloatField(blank=True, null=True)),
                ('Y1987', models.FloatField(blank=True, null=True)),
                ('Y1988', models.FloatField(blank=True, null=True)),
                ('Y1989', models.FloatField(blank=True, null=True)),
                ('Y1990', models.FloatField(blank=True, null=True)),
                ('Y1991', models.FloatField(blank=True, null=True)),
                ('Y1992', models.FloatField(blank=True, null=True)),
                ('Y1993', models.FloatField(blank=True, null=True)),
                ('Y1994', models.FloatField(blank=True, null=True)),
                ('Y1995', models.FloatField(blank=True, null=True)),
                ('Y1996', models.FloatField(blank=True, null=True)),
                ('Y1997', models.FloatField(blank=True, null=True)),
                ('Y1998', models.FloatField(blank=True, null=True)),
                ('Y1999', models.FloatField(blank=True, null=True)),
                ('Y2000', models.FloatField(blank=True, null=True)),
                ('Y2001', models.FloatField(blank=True, null=True)),
                ('Y2002', models.FloatField(blank=True, null=True)),
                ('Y2003', models.FloatField(blank=True, null=True)),
                ('Y2004', models.FloatField(blank=True, null=True)),
                ('Y2005', models.FloatField(blank=True, null=True)),
                ('Y2006', models.FloatField(blank=True, null=True)),
                ('Y2007', models.FloatField(blank=True, null=True)),
                ('Y2008', models.FloatField(blank=True, null=True)),
                ('Y2009', models.FloatField(blank=True, null=True)),
                ('Y2010', models.FloatField(blank=True, null=True)),
                ('Y2011', models.FloatField(blank=True, null=True)),
                ('Y2012', models.FloatField(blank=True, null=True)),
                ('Y2013', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
